backend:
  name: git-gateway

publish_mode: editorial_workflow
media_folder: static/assets
public_folder: assets

collections:
  - name: pattern
    label: Pattern
    folder: src/pattern
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - label: Category
        name: category
        widget: select
        options: ["Getting input", "Navigation", "Dealing with data", "Social", "Miscellaneous", "Onbaording"]
      - { name: subcategory, label: Subcategory, widget: string}
      - label: Tags
        name: tags
        widget: list
        field: { name: tag, label: Tag }
      - { name: caption, label: Caption, widget: string}
      - { name: problem, label: Problem, widget: markdown }
      - { name: solution, label: Solution, widget: markdown }
      - { name: usage, label: Usage, widget: markdown }
      - { name: accessibility, label: Accessibility, widget: markdown }
      - label: Assets
        required: false
        name: assets
        widget: list
        fields:
          - label: Asset
            required: false
            name: asset
            widget: object
            fields:
              - {label: Image, name: image, widget: image, required: false}
              - {label: Caption, name: caption, widget: string, required: false}
      - label: References
        required: false
        name: references
        widget: list
        fields:
          - label: Reference
            required: false
            name: reference
            widget: object
            fields:
              - {label: Title, name: title, required: false}
              - {label: Description, name: description, widget: text, required: false}
              - {label: URL, name: url, widget: string, required: false}